### ISSUE TITLE
Gift product disappear on checkout

### ISSUE THREAD

**Issue by mvsucupira** [ProxiBlue/GiftPromo#1]
Hi, i'm testing this extension and occurs that the gift product is disappearing when i'm going to checkout. I'm using a third party magento checkout module (https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro) but I unable to check if are any conflict.

Anyone could help?

**Comment by ProxiBlue** [comment]
Hi.

Did you test to see if this happens using normal magento checkout? So to determine if the checkout is the issue?

**Comment by josealgardataborges** [comment]
I have same issue, on a simple rule:

"buy 3 products and get the cheapest free" like these [http://prntscr.com/ejwzcn](http://prntscr.com/ejwzcn) 

The product quantity is decreased to 2, but the 1 'free' gift is not shown.

@ProxiBlue In your opinion what is the best way to configure such a rule?

**Comment by josealgardataborges** [comment]
like these [http://prntscr.com/ejwzcn](url)

**Comment by ProxiBlue** [comment]
Ok, so this seems to happen with some installs, and the reason is usually varied. Sometimes due to module conflicts (check if there are rewrite conflicts with other modules)

The best way to debug this, is by the following process. Please note that this is quite extensive, so you need to be using a debugger (xdebug) with and IDE (PHPStorm or something else that can give you a callstack to trace back with)

All cart removals go through this event:

https://github.com/ProxiBlue/GiftPromo/blob/master/app/code/community/ProxiBlue/GiftPromo/Model/Sales/Observer.php#L114

You would want to set your breakpoint on line 117. This is not the actual code that effects the removal of the item. This code is tripped when a delete request has already been issued. It deals with the actual removal.

The plan is to trace back, to where the actual request to remove the item was issues (could be in another module even)

SO, no, with the breakpoint active, you can use the call-stack to trace back, and find a call to ->removeItem() somewhere along the callstack.

ALTERNATIVE METHOD.

It is *most* likely the remove request come from within the validator file. SOmthing in there is tripping a removal. Some condition that is causing a flse positive, and telling the code to now remove the gift.

So essentially when the gift is added, the rules validate, then something happend, and the rule is no longer considered as valid, and then trips a removal.

See this file:

https://github.com/ProxiBlue/GiftPromo/blob/master/app/code/community/ProxiBlue/GiftPromo/Model/Promo/Validator.php

Within it look for all lines of code that does :

```->removeItem```

calls.

Place a breakpoint on each, and find which one is tripping.

From that you can then analyse the code surrounding the trip, and determine what the conditional is failing, why it is causing a delete to trip.

I hope that helps.
